text = input("Enter text to write to the file: ")
file = open("output.txt", "a")
file.write(text)
file.close()
print("Data successfully written to output.txt.")
text2 = input("Enter additional text to append:")
file = open("output.txt", "a")
file.write(text2)
file.close()
print("Data successfully appended to output.txt.")
file = open("output.txt", "r")
content = file.read()
print("Final content of output.txt: ")
print(content)
